apiVersion: apps/v1
kind: Deployment
metadata:
  name: rso16-sv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rso16-sv
  template:
    metadata:
      labels:
        app: rso16-sv
    spec:
      containers:
        - image: bi4528/rso16-sv:latest
          name: rso16-sv
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: server
---
apiVersion: v1
kind: Service
metadata:
  name: rso16-sv-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: rso16-sv
